name: covid19
description: An app for tracking COVID cases across the globe and counties

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  intl: ^0.16.1
  splashscreen: ^1.2.0
  progress_indicators: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: MyIcons
      fonts:
        - asset: icons/MyIcons.ttf

    - family: MyFont
      fonts:
        - asset: font/Ubuntu.ttf